#Wurfelt --- ErisBase Remake
#Best Basic Plugin for 1.8+ Server
#Author: Misoryan & EmptyIrony
#变量区分大小写 /wurfelt reload重载配置文件 <3

Commands:
  permission-denied: '&cPermission Denied.'
  current-usage: '&cCurrent Usage: &4'
  player-offline: '&cTargeted player is offline.'

GMCommand:
  enable: false
Teleport:
  enable: true
Broadcast:
  enable: true
  prefix: '&8[&3Alert&8] &7'
Vanish:
  #Permission: Wurfelt.Vanish
  enable: false
freeze:
  enable: true
  title: '&cCLIENT CHECK REQUEST'
  freeze-other-message: '&7You froze &f[PLAYER] &7.'
  unfreeze-other-message: '&7You froze &f[PLAYER] &7.'
  freeze-message: '&7Your client are now &c&lFROZEN &7by a stuff.'
  unfreeze-message: '&7Your client are now &a&lUNFROZEN &7by a stuff.'
  lore:
    - ' '
    - '&7您目前已被 &f[OPERATOR] &7锁定了客户端&7.'
    - '&7请配合我们完成客户端检查:'
    - ' '
    - '&7QQ群: &f828639514'
    - '&7Discord: &fhttps://discord.gg/R2XDZ3E'
    - ' '
    - '&7我们怀疑您正在使用不被允许的修改,请配合我们进行检查.'
    - '&c&l强制退出游戏会导致你被永久封禁!!!'
    - ' '
    - '&3Wurfelt @ 2019'
  disconnect:
    #false = show to op
    showtoall: false
    message:
      - ' '
      - ' &7Wurfelt &f移除了一名在线玩家'
      - ' &f因为其 &c拒绝客户端检查 &f.'
      - ' '
    command: 'ban [PLAYER] 30d 拒绝客户端检查'
report:
  status:
    waiting: '&cWAITING'
    dealing: '&6DEALING'
    closed: '&4CLOSED'
    done: '&aDONE'
  already-reported: '&7This player is already reported by others. Thanks for your report.'
  report-success: '&7You successfully reported &f%player% &7,thanks for your report.'